FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.9

RUN elasticsearch-plugin install analysis-nori

COPY config/elasticsearch/indices /usr/share/elasticsearch/config/indices
COPY config/elasticsearch/init-index.sh /usr/share/elasticsearch/config/elasticsearch/
RUN chmod +x /usr/share/elasticsearch/config/elasticsearch/init-index.sh

ENV discovery.type=single-node
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false

USER elasticsearch

CMD ["/usr/share/elasticsearch/bin/elasticsearch"]