FROM docker.elastic.co/elasticsearch/elasticsearch:7.17.9

# 데이터 디렉토리 권한 설정
RUN mkdir -p /usr/share/elasticsearch/data && \
    chown -R elasticsearch:elasticsearch /usr/share/elasticsearch/data && \
    chmod 777 /usr/share/elasticsearch/data

# nori 플러그인 설치
RUN elasticsearch-plugin install analysis-nori

USER elasticsearch

ENV discovery.type=single-node
ENV ES_JAVA_OPTS="-Xms512m -Xmx512m"
ENV xpack.security.enabled=false

CMD ["eswrapper"]